version: "3.9"
services:
  nginx-proxy-manager:
    container_name: nginx-proxy-manager
    image: "jc21/nginx-proxy-manager:latest"
    user: "1000:1000"
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    environment:
      DB_SQLITE_FILE: "/data/database.sqlite"
      TZ: "Europe/Paris"
    volumes:
      - /home/tio/config/nginx-proxy-manager:/data
      - /home/tio/config/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - nginx-proxy
    healthcheck:
      # test: ["curl", "-f", "http://localhost"]
      test: ["CMD", "/bin/check-health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 30s
networks:
  nginx-proxy:
    name: nginx-proxy
    driver: bridge